name: Build
on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/head/main' }}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm & deps
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v3

      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: NX_BRANCH=$GITHUB_HEAD_REF npx nx affected --target=lint --parallel=5

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm & deps
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v3

      - run: pnpm install --frozen-lockfile

      - name: Run Vitest
        run: NX_BRANCH=$GITHUB_HEAD_REF npx nx affected --target=test:unit --parallel=5

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm & deps
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v3

      - run: pnpm install --frozen-lockfile

      - run: npx playwright install-deps && npx playwright install

      - name: Run Playwright
        run: NX_BRANCH=$GITHUB_HEAD_REF npx nx affected --target=test:e2e --parallel=5

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm & deps
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v3

      - run: pnpm install --frozen-lockfile

      - name: Build
        if: steps.cache-dist.outputs.cache-hit != 'true'
        run: NX_BRANCH=$GITHUB_HEAD_REF npx nx build app

      - name: Cache dist
        id: cache-dist
        uses: actions/cache@v3
        env:
          cache-name: cache-dist
        with:
          path: packages/app/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pnpm-lock.yaml') }}

  release:
    name: Create new version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # fetch all commits in history (default is only 1 commit)
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Release version
        uses: changesets/action@v1
        with:
          version: pnpm release:apply
