name: Release
on:
  push:
    branches:
      - main
  pull_request: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: release-please
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # fetch all commits in history (default is only 1 commit)
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: essencium-frontend
          bump-minor-pre-major: true
          extra-files: |
            [
              {
                "type": "json",
                "path": "${{ github.workspace }}/packages/app/package.json",
                "jsonpath": "version"
              }
            ]
          # DEBUGGING to not hit rate limits
          release-search-depth: 10
          commit-search-depth: 10

      # - name: Sync versions
      #   run: pnpm sync-versions
